# -*- coding: utf-8 -*-
"""Atm360_FS_matching.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16DOpP7TIqF_T2_e9KlmjdbCP2FIAvXHg
"""

pip install faker

pip install --upgrade onnxmltools skl2onnx

import faker
import pandas as pd
import numpy as np
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
import onnxmltools
import onnx
from onnxmltools.convert import convert_xgboost
from skl2onnx import convert_sklearn
from skl2onnx.common.data_types import FloatTensorType

num_datapoints = 10000

sm_vals = [0,1]
sm_probs = [0.3, 0.7]

data = [None]*num_datapoints
for i in range(num_datapoints):
  sm = int(np.random.choice(sm_vals, p=sm_probs))
  td = np.random.random()*60
  rev = np.random.random()*5
  sev = np.random.random()*4
  score = (0.55*sm) + (0.2*(td/60)) + (0.1*(rev/5)) - (0.1*(sev/4)) + (0.15*np.random.random())
  data[i] = {'skill_match': sm,
             'travel_distance': td,
             'engineer_avg_review': rev,
             'severity': sev,
             'score': score
             }

dataF = pd.DataFrame(data)

dataF

test = dataF['score']
train = dataF.drop('score', axis=1)

X_train, x_test, Y_train, y_test = train_test_split(train, test, test_size=0.2, random_state=42)

model = xgb.XGBRegressor(objective='reg:squarederror',
                             n_estimators=50,
                             learning_rate=0.1,
                             max_depth=5,
                             random_state=42)
model.fit(X_train, Y_train)

mean_squared_error(model.predict(x_test), y_test)

model.predict(x_test)[:5]

model.save_model("engineer_recommend.json")

y_test[:5]

initial_type = [('float_input', FloatTensorType([None, X_train.shape[1]]))]
onnx_model = onnxmltools.convert.convert_xgboost(
    model,
    initial_types=initial_type
)

xgb.__version__