// --- Core Data Models for ATM360 ---
// This file defines the core data structures for the project.
// All services, controllers, and API routes should reference these types.

/**
 * Represents the banking institution.
 * This is the top-level entity.
 */
export interface Bank {
  id: string;
  name: string;
  shortCode: string; // e.g., "ZENITH", "GTB"
  headOfficeAddress?: string;
  contactEmail?: string;
  contactPhone?: string;
  regionCoverage?: string[];
  createdAt: string;
  updatedAt: string;
}

// --- NEW AUTHENTICATION & PROFILE MODELS ---

/**
 * Represents an authenticated user in the system.
 * This model holds login and role information.
 * UPDATED: Added the "CUSTOMER" role.
 */
export interface User {
  id: string;
  email: string; // The primary login field
  password: string; // This exists in the DB, not sent to client
  role: "ADMIN" | "ENGINEER" | "CUSTOMER"; // <-- Now includes CUSTOMER
  createdAt: string;
  updatedAt: string;
}

/**
 * Profile for a Bank Administrator (Ops user).
 * Linked to a User account.
 */
export interface BankAdministrator {
  id: string;
  userId: string; // Foreign key to User.id
  name: string;
  phone: string;
  bankId: string; // Foreign key to Bank.id
  permissions: ("VIEW_REPORTS" | "DISPATCH_ENGINEERS" | "MANAGE_USERS")[];
  createdAt: string;
  updatedAt: string;
}

/**
 * Represents the field engineer responsible for maintenance.
 * MODIFIED: Added userId to link to the User model.
 */
export interface Engineer {
  id: string;
  userId: string; // Foreign key to User.id
  name: string;
  employeeCode: string;
  phone: string;
  email: string; // Operational contact email (User.email is for login)
  region: string; // e.g., "Lagos Mainland"
  specialization: ("NETWORK" | "HARDWARE" | "POWER" | "SOFTWARE")[];
  currentStatus: "AVAILABLE" | "ON_ASSIGNMENT" | "OFFLINE";
  assignedTickets?: string[]; // list of Ticket IDs
  performance: {
    avgResponseTimeMins: number;
    avgResolutionTimeMins: number;
    totalTicketsResolved: number;
    uptimeContributionPercent: number;
    rating: number; // gamified performance (0–5)
  };
  lastKnownLocation?: {
    lat: number;
    lng: number;
    lastUpdated: string;
  };
  createdAt: string;
  updatedAt: string;
}

/**
 * NEW: Profile for a Customer (End-User).
 * Linked to a User account.
 */
export interface CustomerProfile {
  id: string;
  userId: string; // Foreign key to User.id
  name: string;
  phone: string; // Verified phone number
  createdAt: string;
  updatedAt: string;
}

// --- CORE OPERATIONAL MODELS ---

/**
 * The core ATM entity, containing all telemetry and status data.
 * This is the merged and cleaned-up definition.
 */
export interface  ATM {
  id: string; // UUID or unique code e.g., "ATM-LAG-0012"
  bankId: string; // reference to Bank entity
  location: {
    branchName?: string;
    address: string;
    lga?: string;
    region: string;
    state: string;
    coordinates: {
      lat: number;
      lng: number;
    };
  };
  model: string; // e.g., NCR SelfServ 80, Diebold Opteva 520
  type: "CASH_DISPENSER" | "FULL_FUNCTION" | "DEPOSIT_ONLY" | "WITHDRAWAL_ONLY";
  status: "ONLINE" | "OFFLINE" | "OUT_OF_CASH" | "MAINTENANCE" | "UNKNOWN";
  lastUpdated: string; // ISO timestamp
  networkStatus: "CONNECTED" | "DISCONNECTED" | "INTERMITTENT";
  cashLevel: {
    totalCapacity: number; // in Naira
    currentAmount: number; // in Naira
    lowThreshold: number; // alert threshold
    emptyThreshold: number; // alert threshold
  };
  powerStatus: {
    mains: boolean;
    generator: boolean;
    inverter: boolean;
    fuelLevel?: number; // percentage
  };
  diagnostics: {
    temperatureC?: number;
    errorCodes?: string[]; // e.g., ["E301", "D404"]
    lastErrorTimestamp?: string;
  };
  predictiveScore?: {
    failureRisk: number; // 0–1 score
    cashOutRisk: number; // 0–1 score
    networkFailureRisk: number; // 0–1 score
  };  
  assignedEngineerId?: string;
  uptimeMetrics?: {
    uptimePercentageLast7Days: number;
    downtimeMinutesThisMonth: number;
  };
  createdAt: string;
  updatedAt: string;
}

/**
 * Represents a customer-filed report about an ATM issue.
 * UPDATED: Can now be linked to an authenticated customer profile.
 */
export interface CustomerReport {
  id: string;
  atmId: string;
  customerProfileId?: string; // Foreign key to CustomerProfile.id
  customerPhone?: string; // Stored if anonymous (USSD/WhatsApp)
  channel: "USSD" | "WHATSAPP" | "MOBILE_APP" | "WEB";
  issueReported: "ATM_DOWN" | "NO_CASH" | "SLOT_JAMMED" | "SCREEN_BLANK" | "OTHER";
  timestamp: string;
  verified?: boolean; // cross-matched with system telemetry
  ticketId?: string; // link to generated ticket
}

/**
 * The core maintenance ticket. Can be generated by the
 * system (telemetry) or a CustomerReport.
 */
export interface Ticket {
  id: string;
  atmId: string;
  engineerId?: string;
  reportedBy: "SYSTEM" | "CUSTOMER" | "BRANCH_MANAGER";
  issueType:
    | "CASH_OUT"
    | "NETWORK_FAILURE"
    | "HARDWARE_ERROR"
    | "POWER_ISSUE"
    | "CARD_JAM"
    | "SCREEN_FAILURE"
    | "OTHER";
  severity: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
  description: string;
  status: "OPEN" | "ASSIGNED" | "IN_PROGRESS" | "RESOLVED" | "ESCALATED" | "CLOSED";
  createdAt: string;
  updatedAt: string;
  resolution?: {
    summary: string;
    resolvedAt: string;
    partsUsed?: string[];
    timeSpentMinutes: number;
    proofPhotoUrl?: string;
  };
  geoValidation?: {
    engineerLat?: number;
    engineerLng?: number;
    validatedAt?: string;
  };
  sourceData?: {
    atmSnapshot?: ATM; // A snapshot of the ATM state when ticket was created
    customerReportId?: string;
  };
}

// --- DTOs & REPORTING MODELS ---

/**
 * Represents an AI-generated suggestion for dispatch.
 * This is a DTO, not necessarily a database table.
 */
export interface DispatchSuggestion {
  id: string;
  atmId: string;
  suggestedEngineerId: string;
  distanceKm: number;
  estimatedTravelTimeMins: number;
  reason: string; // e.g., "Nearest available engineer with hardware expertise"
  timestamp: string;
}

/**
 * Represents a high-level performance report for bank management.
 * This is a DTO, not necessarily a database table.
 */
export interface PerformanceReport {
  id: string;
  bankId: string;
  period: {
    start: string;
    end: string;
  };
  metrics: {
    totalATMs: number;
    activeATMs: number;
    averageUptimePercent: number;
    averageResponseTimeMins: number;
    totalTicketsCreated: number;
    totalTicketsResolved: number;
    topPerformingEngineerIds: string[];
    mostProblematicRegions: string[];
    downtimeByCause: Record<string, number>; // { "CASH_OUT": 1200, "NETWORK_FAILURE": 900 }
  };
  generatedAt: string;
}



export interface TelemetryPacket {
  atmId: string; // Which ATM is this from?
  timestamp: string; // When was this packet generated?

  // --- Core Status ---
  // The ATM's self-reported overall status
  status: "ONLINE" | "OFFLINE" | "OUT_OF_CASH" | "MAINTENANCE" | "UNKNOWN";
  networkStatus: "CONNECTED" | "DISCONNECTED" | "INTERMITTENT";

  // --- Resource Levels ---
  cashLevel: {
    currentAmount: number;
    // You could add 'cassette1Status', 'cassette2Status', etc. here
  };
  powerStatus: {
    mains: boolean;
    generator: boolean;
    inverter: boolean;
  };

  // --- Diagnostics ---
  // A snapshot of the internal sensor readings
  diagnostics: {
    temperatureC?: number;
    errorCodes?: string[]; // e.g., ["E301", "D404"]
  };
}